findElemnt.py
This is my 1st commit to this repository for String Operation
=> First Commit

LinearSearch.Cpp
This is my second commit to  this repository
=> Second commit

mergesort.java, stack1.java
This is my 3rd commit to this repository , I have added the stack program
=> Third commit

2sum.cpp
Signed-off-by: AyushR1 <ayushrathore12501@gmail.com>
=> Add C++ solution of 2 sum problem

trie-implementation.cpp, word-occurrence-and-number-of-word-with given-prefix.cpp
Basic Trie implementation program added in C++.
=> trie implementation program

longest-word-with-all-substring-present.cpp
A program to find the longest word in the trie whose all substring are present in C++.
=> longest word in the array of whose all the substring are present

find_duplicate_number.java
=> Find Duplicate Number in an array

Table.cpp
This code uses the DSA concept.
=> Added Table.cpp

matrix_zeroes.cpp
This is the matrix zeroes problem where we change the row and column elements of a zero occurring element in a matrix.
Please accept this pull request for Hacktoberfest-22
=> Add Matrix Zeroes problem

Quicksort.java
This is a new commit made by me to this repository
=> new commit

climbing-stairs.cpp, house-robber.cpp
Signed-off-by: AyushR1 <ayushrathore12501@gmail.com>
=> Add C++ code for Climibing Stairs

Palindrome Partitioning II.cpp
=> Create Palindrome Partitioning II.cpp

longestuniquecharsubstring.cpp
Problem : Given a string you need to print the size of the longest possible substring that has exactly K unique characters. If there is no possible substring then print -1.
=> Added longestuniquecharsubstring.cpp

longest-string-with-all-possible-prefix.cpp
A program to Find the longest string with all the possible prefixes in C++.
=> Longest string with all possible prefixes

DFS.cpp
A programmatic implementation of Depth First Search!
=> Depth First Search Algorithm

beginner.cpp
=> Hacktoberfest2022

Convert Sorted List to Binary Search Tree.cpp
=> Create Convert Sorted List to Binary Search Tree.cpp

Saitama.cpp
=> Added Saitama.cpp

q1.java
https://www.codechef.com/submit/NEWPIECE
Please  label my request with Hacktoberfest22 before merging.
=> Codechef problems

ordered set/code1.cpp, ordered set/code2.cpp, ordered set/readme.txt
Problem statement is: We have to find all elements which are minimum that any element in O(logn) time complexity for each operation.
There are two code files here: 
code1 is using segment tree and code2 is using ordered set
=> Add ordered_set.cpp

fibonacci-number.cpp
Signed-off-by: AyushR1 <ayushrathore12501@gmail.com>
=> C++ code for fibonacci no.

maps.cpp
Implementation of Maps in C++ STL
=> Maps Added

Binary Search Tree.cpp
Binary search tree- Insertion, Search, Traversal, FindMin, FindMax, Delete
=> Binary Search Tree

A.2_3 moves.cpp
Added codeforces problem A.2_3 moves.cpp
=> Added A.2_3 moves.cpp

code1.cpp, code10.cpp, code11.cpp, code12.cpp, code13.cpp, code14.cpp, code15.cpp, code16.cpp, code17.cpp, code18.cpp, code19.cpp, code2.cpp, code20.cpp, code3.cpp, code4.cpp, code5.cpp, code6.cpp, code7.cpp, code8.cpp, code9.cpp, readme.txt
This file contains all the graph algorithms 
Readme file contains which code is for which algorithm
=> Add graph files

NQueenProblem.java
Java program to solve N Queen Problem using backtracking
=> Added NQueenProblem.java

word-break.cpp
A program to implement dynamic programming algorithm in C++.
=> word-break

Part-2/Learning Programs/binarytree.cpp, Part-2/Learning Programs/bubblesort.cpp, Part-2/Learning Programs/complexclass.cpp, Part-2/Learning Programs/stackusingLl.cpp, countanddelete.cpp, countduplicates.cpp, countinversion.cpp, decodeways.cpp, doublypalindrome.cpp
add interview level questions and concepts
=> added problems and concepts

HLD.cpp, LcaSparceMin.cpp
Program for Lca Sparce tree (minimum) in c++.
=> Program for Lca Sparce tree (minimum)

regular expressions
Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where:
'.' Matches any single character.​​​​
'*' Matches zero or more of the preceding element.
=> regular expressions

16.LiLi4.c
=> Linked list operation in switch case
